#!/bin/bash
####################################
#           Hi     :)              #
####################################

if [[ ! -v DB_ENVIRONMENT ]]; then
    echo 'DB_ENVIRONMENT undefined, development settings selected.'
    DB_CONF="development"
elif [[ -z "$DB_ENVIRONMENT" ]]; then
    echo 'DB_ENVIRONMENT empty, development settings selected.'
    DB_CONF="development"
else
    echo "DB_ENVIRONMENT = $DB_ENVIRONMENT"
    DB_CONF="$DB_ENVIRONMENT"
fi

if [ "$DB_CONF" == "development" ]; then
    DB_FILE=`grep "$DB_CONF" -C 7 api/knexfile.js | grep filename | xargs -- | awk '{print $2}'| grep -Po '^.{3}\K.*' | sed 's/.\{1\}$//'`
    if [ ! -f "$DB_FILE" ]; then
        echo "Creating a new database at $DB_FILE"
        cd api && npx knex migrate:latest && npx knex seed:run
        cd ..
    else
        echo "Database: $DB_FILE"
    fi
fi

START_BACKEND="cd api && npm start"
START_FRONTEND="cd client && npm start"
npx concurrently "$START_BACKEND" "$START_FRONTEND"
